branch-defaults:
  default:
    environment: reader-env
    group_suffix: null
environment-defaults:
  reader-env:
    branch: null
    repository: null
global:
  application_name: Reader
  branch: null
  default_ec2_keyname: aws-reader
  default_platform: arn:aws:elasticbeanstalk:ap-south-1::platform/Python 3.6 running
    on 64bit Amazon Linux/2.7.0
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
