# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 20:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminacc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('3 days', '3 days'), ('7 days', '7 days'), ('14 days', '14 days'), ('21 days', '21 days'), ('1 month', '1 month'), ('1.5 months', '1.5 months'), ('2 months', '2 months'), ('3 months', '3 months'), ('4 months', '4 months'), ('5 months', '5 months'), ('6 months', '6 months'), ('12 months', '12 months'), ('18 months', '18 months'), ('24 months', '24 months'), ('Buy', 'Buy')], default='1 month', max_length=255)),
                ('nprice', models.FloatField(default=0)),
                ('itime', models.DateTimeField(default=datetime.datetime.now)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ebooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.FloatField()),
                ('pages', models.IntegerField()),
                ('content', models.FileField(blank=True, default='', upload_to='media/')),
                ('link', models.URLField(blank=True, default='')),
                ('img', models.ImageField(default='', upload_to='images/')),
                ('dayopt', multiselectfield.db.fields.MultiSelectField(choices=[('3 days', '3 days'), ('7 days', '7 days'), ('14 days', '14 days'), ('21 days', '21 days'), ('1 month', '1 month'), ('1.5 months', '1.5 months'), ('2 months', '2 months'), ('3 months', '3 months'), ('4 months', '4 months'), ('5 months', '5 months'), ('6 months', '6 months'), ('12 months', '12 months'), ('18 months', '18 months'), ('24 months', '24 months')], default='3 days,7 days,14 days,21 days,1 month,1.5 months,2 months,3 months,4 months,5 months,6 months', max_length=123)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi')], default='English', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5)),
                ('bookActive', models.CharField(choices=[('bookActive', 'bookActive'), ('bookInactive', 'bookInactive')], default='bookActive', max_length=20)),
                ('isbn', models.CharField(default='', max_length=14)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rapp.Authors')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Gmailid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lastpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rapp.Ebooks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subemail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnid', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Uploaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('handled', models.BooleanField(default=False)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rapp.Publishers')),
            ],
        ),
        migrations.CreateModel(
            name='Usercart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('3 days', '3 days'), ('7 days', '7 days'), ('14 days', '14 days'), ('21 days', '21 days'), ('1 month', '1 month'), ('1.5 months', '1.5 months'), ('2 months', '2 months'), ('3 months', '3 months'), ('4 months', '4 months'), ('5 months', '5 months'), ('6 months', '6 months'), ('12 months', '12 months'), ('18 months', '18 months'), ('24 months', '24 months')], max_length=255)),
                ('nprice', models.FloatField(default=0)),
                ('buyrent', models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent')], default='Rent', max_length=10)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rapp.Ebooks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub', models.BooleanField(default=False)),
                ('benname', models.CharField(blank=True, max_length=255)),
                ('account', models.CharField(blank=True, max_length=255)),
                ('ifsc', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(blank=True, max_length=255)),
                ('publisher', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='rapp.Publishers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rapp.Ebooks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ebooks',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rapp.Publishers'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='ebook',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='rapp.Ebooks'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authors',
            name='publisher_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='rapp.Publishers'),
        ),
    ]
