# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebooks',
            name='deal',
        ),
        migrations.AddField(
            model_name='ebooks',
            name='buyrent',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent')], default='Rent', max_length=10),
        ),
    ]
