# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0003_auto_20180510_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebooks',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi')], default='English', max_length=30),
        ),
    ]
