# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0003_auto_20181101_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooks',
            name='publishdate',
            field=models.DateField(blank=True),
        ),
    ]
