# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0004_auto_20181101_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebooks',
            name='publishdate',
        ),
        migrations.RemoveField(
            model_name='ebooks',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
