# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0004_ebooks_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebooks',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
