# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0005_ebooks_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='duration',
            field=models.CharField(choices=[('3 days', '3 days'), ('7 days', '7 days'), ('14 days', '14 days'), ('21 days', '21 days'), ('1 month', '1 month'), ('1.5 months', '1.5 months'), ('2 months', '2 months'), ('3 months', '3 months'), ('4 months', '4 months'), ('5 months', '5 months'), ('6 months', '6 months'), ('12 months', '12 months'), ('18 months', '18 months'), ('24 months', '24 months'), ('Buy', 'Buy')], default='1 month', max_length=255),
        ),
        migrations.AlterField(
            model_name='ebooks',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
