# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0006_auto_20181101_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooks',
            name='publishdate',
            field=models.DateField(null=True),
        ),
    ]
