# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0008_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastpage',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
