# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0009_lastpage_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebooks',
            name='priority',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5),
        ),
    ]
