# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 18:14
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0012_auto_20180513_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooks',
            name='dayopt',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('3 days', '3 days'), ('7 days', '7 days'), ('14 days', '14 days'), ('21 days', '21 days'), ('1 month', '1 month'), ('1.5 months', '1.5 months'), ('2 months', '2 months'), ('3 months', '3 months'), ('4 months', '4 months'), ('5 months', '5 months'), ('6 months', '6 months'), ('12 months', '12 months'), ('18 months', '18 months'), ('24 months', '24 months')], default='3 days,7 days,14 days,21 days,1 month,1.5 months,2 months,3 months,4 months,5 months,6 months', max_length=123),
        ),
    ]
