# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0012_auto_20181101_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooks',
            name='tags',
            field=models.ManyToManyField(blank=True, to='rapp.Tag'),
        ),
    ]
