# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rapp', '0014_ebooks_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminacc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userp',
            name='account',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userp',
            name='benname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userp',
            name='ifsc',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
