# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0015_auto_20180821_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gmailid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='userp',
            name='number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
