# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0015_auto_20180818_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebooks',
            name='isbn',
        ),
    ]
