# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0016_remove_ebooks_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebooks',
            name='isbn',
            field=models.CharField(default='', max_length=14),
        ),
    ]
