# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0017_musiclis'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiclis',
            name='queue',
            field=models.BooleanField(default=True),
        ),
    ]
