# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0020_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='color',
            field=models.CharField(choices=[('rgb(255, 237, 165)', 'rgb(255, 237, 165)'), ('rgb(219, 255, 183)', 'rgb(219, 255, 183)'), ('rgb(255, 219, 219)', 'rgb(255, 219, 219)'), ('rgb(201, 237, 237)', 'rgb(201, 237, 237)')], default='rgb(255, 237, 165)', max_length=255),
        ),
    ]
