# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0024_bookmark_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='selectedtext',
            field=models.TextField(default=''),
        ),
    ]
