# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0026_notefile_notefileitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooks',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ebooks',
            name='isbn',
            field=models.CharField(default='', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='ebooks',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rapp.Publishers'),
        ),
    ]
