# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0028_uploadadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catmodel',
            field=models.CharField(choices=[('3month', '3month'), ('12month', '12month')], default='3month', max_length=20),
        ),
    ]
