# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0029_category_catmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyvalue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='ebooks',
            name='content',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='ebooks',
            name='img',
            field=models.URLField(default=''),
        ),
    ]
