# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0030_auto_20181201_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooks',
            name='publisher',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rapp.Publishers'),
        ),
    ]
