# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0031_auto_20181201_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooks',
            name='content',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ebooks',
            name='img',
            field=models.CharField(default='', max_length=255),
        ),
    ]
