# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0032_auto_20181203_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=255)),
                ('name2', models.CharField(max_length=255)),
                ('ebooks', models.ManyToManyField(to='rapp.Ebooks')),
            ],
        ),
    ]
