# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 05:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0034_auto_20181204_0549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='percentval',
            new_name='offerhighlimit',
        ),
        migrations.AddField(
            model_name='offer',
            name='offerlowlimit',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='offer',
            name='percentbool',
            field=models.BooleanField(default=True),
        ),
    ]
