# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0035_auto_20181204_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ebooks', models.ManyToManyField(to='rapp.Ebooks')),
            ],
        ),
    ]
