# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0039_auto_20181217_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastpage',
            name='page',
        ),
        migrations.AddField(
            model_name='lastpage',
            name='epubcfi',
            field=models.TextField(default=''),
        ),
    ]
