# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0041_readlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentageread',
            name='percent',
            field=models.FloatField(null=True),
        ),
    ]
