# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0043_ipaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ipaddress',
        ),
    ]
