# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0046_connectionhistory_echo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionhistory',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
