# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-07 05:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rapp', '0051_auto_20181221_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptiontry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(max_length=255)),
                ('publicip', models.CharField(max_length=255)),
                ('subplan', models.IntegerField()),
                ('subtime', models.IntegerField(choices=[(1, 1), (3, 3), (6, 6), (12, 12)], default=1)),
                ('amount', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('purchased', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
