# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0054_lastpagesample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendedbooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rapp.Ebooks')),
            ],
        ),
    ]
