# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0055_recommendedbooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedbooks',
            name='ebook',
        ),
        migrations.DeleteModel(
            name='Recommendedbooks',
        ),
    ]
