# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rapp', '0056_auto_20190110_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyid', models.CharField(max_length=255)),
                ('duration', models.CharField(choices=[('3 days', '3 days'), ('7 days', '7 days'), ('14 days', '14 days'), ('21 days', '21 days'), ('1 month', '1 month'), ('1.5 months', '1.5 months'), ('2 months', '2 months'), ('3 months', '3 months'), ('4 months', '4 months'), ('5 months', '5 months'), ('6 months', '6 months'), ('12 months', '12 months'), ('18 months', '18 months'), ('24 months', '24 months'), ('Buy', 'Buy')], default='1 month', max_length=255)),
                ('amount', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('purchased', models.BooleanField(default=False)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rapp.Ebooks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
