from django.contrib import admin
from rapp.models import Authors,Publishers,Ebooks,UserP,Adminacc,Subscribers,Category,Usercart,Wishlist,Dashboard,Transactions,Notes,Lastpage,Uploaded,Gmailid,Bookmark,Tag,Musicgenre,Musictag,Music,Musiclis,Playlist,Highlight,Notefile,Notefileitem,Uploadadmin,Keyvalue


admin.site.register(Authors)
admin.site.register(Publishers)
admin.site.register(Ebooks)
admin.site.register(UserP)
admin.site.register(Subscribers)
admin.site.register(Category)
admin.site.register(Usercart)
admin.site.register(Wishlist)
admin.site.register(Dashboard)
admin.site.register(Transactions)
admin.site.register(Notes)
admin.site.register(Lastpage)
admin.site.register(Uploaded)
admin.site.register(Adminacc)
admin.site.register(Gmailid)
admin.site.register(Bookmark)
admin.site.register(Tag)
admin.site.register(Musicgenre)
admin.site.register(Musictag)
admin.site.register(Music)
admin.site.register(Musiclis)
admin.site.register(Playlist)
admin.site.register(Highlight)
admin.site.register(Notefile)
admin.site.register(Notefileitem)
admin.site.register(Uploadadmin)
admin.site.register(Keyvalue)