from django.contrib import admin
from rapp.models import Authors,Publishers,Ebooks,UserP,Adminacc,Subscribers,Category,Usercart,Wishlist,Dashboard,Transactions,Notes,Lastpage,Uploaded,Gmailid,Bookmark,Tag,Musicgenre,Musictag,Music,Musiclis,Playlist,Highlight,Notefile,Notefileitem,Uploadadmin,Keyvalue,Offer,Bestseller,Detailview,Readview,Sampleview,Genreview,Newreleaseview,Bestsellerview,Searchview,Rateduser,Percentageread,Readlocation,ConnectionHistory,Payment,Publisherpayment


admin.site.register(Authors)
admin.site.register(Publishers)
admin.site.register(Ebooks)
admin.site.register(UserP)
admin.site.register(Subscribers)
admin.site.register(Category)
admin.site.register(Usercart)
admin.site.register(Wishlist)
admin.site.register(Dashboard)
admin.site.register(Transactions)
admin.site.register(Notes)
admin.site.register(Lastpage)
admin.site.register(Uploaded)
admin.site.register(Adminacc)
admin.site.register(Gmailid)
admin.site.register(Bookmark)
admin.site.register(Tag)
admin.site.register(Musicgenre)
admin.site.register(Musictag)
admin.site.register(Music)
admin.site.register(Musiclis)
admin.site.register(Playlist)
admin.site.register(Highlight)
admin.site.register(Notefile)
admin.site.register(Notefileitem)
admin.site.register(Uploadadmin)
admin.site.register(Keyvalue)
admin.site.register(Offer)
admin.site.register(Bestseller)
admin.site.register(Detailview)
admin.site.register(Readview)
admin.site.register(Sampleview)
admin.site.register(Genreview)
admin.site.register(Newreleaseview)
admin.site.register(Bestsellerview)
admin.site.register(Searchview)
admin.site.register(Rateduser)
admin.site.register(Percentageread)
admin.site.register(Readlocation)
admin.site.register(ConnectionHistory)
admin.site.register(Payment)
admin.site.register(Publisherpayment)